#pragma once

//Create event codes
#define EVENT_DEFAULT           0
#define EVENT_SOUD              1
#define EVENT_ENEMYDEAD         2
#define EVENT_BUY_WEAPON        3
#define EVENT_ROUND             4
#define EVENT_PLAYER_DAMAGED    5
#define EVENT_M1KE_COMPLETE     6
#define EVENT_RESPAWN_ENEMY     7
#define EVENT_BREAK_ELECTRIC_PANEL_GOAL     8
#define EVENT_SPAWN_NEW_ENEMY   9
// #define EVENT_BUY_BASICGUN      4
// #define EVENT_BUY_REVOLVER      8
// #define EVENT_BUY_AUTOMATICGUN  16
// #define EVENT_BUY_SUBMACHINEGUN 32
// #define EVENT_BUY_ASSAULTRIFLE  64
// #define EVENT_BUY_RIFLE         128
// #define EVENT_BUY_RAYGUN        256
// #define EVENT_BUY_COMBATSHOTGUN 512
// #define EVENT_BUY_SHOTGUN       1024
// #define EVENT_BUY_MACHINEGUN    2048

// #define EVENT_BUY_WEAPON EVENT_BUY_BASICGUN | EVENT_BUY_REVOLVER | EVENT_BUY_AUTOMATICGUN | EVENT_BUY_SUBMACHINEGUN | EVENT_BUY_ASSAULTRIFLE | EVENT_BUY_RIFLE | EVENT_BUY_RAYGUN | EVENT_BUY_COMBATSHOTGUN | EVENT_BUY_SHOTGUN | EVENT_BUY_MACHINEGUN