#pragma once

//Types of collisions
#define DEFAULT_COLLISION           0
#define PLAYER_COLLISION            1
#define ENEMY_COLLISION             2
#define SOLID_COLLISION             4
#define ATTACK_COLLISION            8
#define TRIGGER_COLLISION           16
#define PROJECTILE_SLOW_COLLISION   32
#define PROJECTILE_SPIT_COLLISION   64
#define DESTROYABLE_COLLISION       128
#define BARREL_COLLISION            256
#define PROJECTILE_ROCKET_COLLISION 512
#define NO_SIGHT_COLLISION          1024

#define ENEMIES_ATTACKS_COLLISION   ATTACK_COLLISION | PROJECTILE_SLOW_COLLISION | PROJECTILE_SPIT_COLLISION
#define NO_TRASPASABLE_COLLISION    SOLID_COLLISION | DESTROYABLE_COLLISION | BARREL_COLLISION
#define SHOT_COLLISION_MASK         ENEMY_COLLISION | SOLID_COLLISION | DESTROYABLE_COLLISION | BARREL_COLLISION
#define ENEMY_ATTACK_MASK           PLAYER_COLLISION | DESTROYABLE_COLLISION
#define ALL_COLLISION               0xFFFF

//Types of colliders
//Vector position
#define SET_COLLIDER_NORMAL  0
#define SET_COLLIDER_HEAD    1
#define SET_COLLIDER_Trigger 2

//Flag in the vector
#define COLLIDER_NORMAL      0
#define COLLIDER_HEAD        1
#define COLLIDER_Trigger     2